<?php
// +--------------------------------------------------------------------------------
// |  [ WE CAN DO IT JUST programmer ]
// +--------------------------------------------------------------------------------
// | Copyright (c) 2010 http://www.hongrs.net All rights reserved.
// +--------------------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +--------------------------------------------------------------------------------
// | Author: lan_chi <lan_chi@qq.com>
// +--------------------------------------------------------------------------------
// $Id$

class inter_menu {

    public static function menu(){
		$items['admin/menu'] = array(
			'type' => MASTER,
			'call_back' => 'get by foem'
		);
		$items['admin/bmenu'] = array('eeeemenu');
		$items['admin/cmenu'] = array('adfffffmmenuin');
		return $items;
    }
    
    public function api() {
        echo '888888888888888888888';
    }
}