<?php
// +--------------------------------------------------------------------------------
// |  [ WE CAN DO IT JUST programmer ]
// +--------------------------------------------------------------------------------
// | Copyright (c) 2010 http://www.hongrs.net All rights reserved.
// +--------------------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +--------------------------------------------------------------------------------
// | Author: lan_chi <lan_chi@qq.com>
// +--------------------------------------------------------------------------------
// $Id$

class intern_menu {
    public static function menu(){
        $items['admin/router'] = array(
            'title' => 'Router',
            'type' => ADMIN_MAIN_MENU,
            'permission' => 'permission',
            'callback' => array(
                'function' => 'api'
             )
        );
        return $items;
    }

    public function api() {
        return 'inter_menu api test';
    }
    public function boot() {
        //echo '888888';
    }
}
