<?php
// +--------------------------------------------------------------------------------
// |  [ WE CAN DO IT JUST programmer ]
// +--------------------------------------------------------------------------------
// | Copyright (c) 2010 http://www.hongrs.net All rights reserved.
// +--------------------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +--------------------------------------------------------------------------------
// | Author: lan_chi <lan_chi@qq.com>
// +--------------------------------------------------------------------------------
// $Id$

class inter_system {
    // menu hook
    public function menu() {
		$items['admin'] = array(
            'type'           => ADMIN_MAIN_MENU,
            'title'          => __('Administrator'),
            'title callback' => '__',
            'description'    => 'Administrator Dashboard',
            'callback'       => array(
                 'template' => 'system.admin.inc'
                 //'function' => array(this, 'callback_function')
            ),
            'widget'         => -1
            
        );
		$items['admin/settings'] = array(
            'type'        => ADMIN_MAIN_MENU,
            'title'       => __('Adminstrter plan'),
            'description' => 'Description here now!',
            'callback'    => array(
                    'function' => 'get_form'
                    //''
                    //'function' => array(this, 'callback_function')
            )
        );
		$items['admin/settings/theme'] = array(
            'type'        => ADMIN_MAIN_MENU,
            'title'       => __('The site theme'),
            'description' => 'Mange theme description here now!',
            'callback'    => array(
                    'template' => 'theme.inc'
            )
        );
		return $items;
    }

    public static function api() {
        echo "system api: \n";
        print_r(func_get_args());
    }
    
    public function boot() {
        //echo '123456';
    }
}