<?php
// +--------------------------------------------------------------------------------
// |  [ WE CAN DO IT JUST programmer ]
// +--------------------------------------------------------------------------------
// | Copyright (c) 2010 http://www.hongrs.net All rights reserved.
// +--------------------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +--------------------------------------------------------------------------------
// | Author: lan_chi <lan_chi@qq.com>
// +--------------------------------------------------------------------------------
// $Id$

class inter_system {
    public function menu() {
		$items['admin/system'] = array('admin');
		$items['admin/b'] = array('eeee');
		$items['admin/c'] = array('adfffffmin');
		return $items;
    }
    
    public static function api() {
        echo "system api: \n";
        print_r(func_get_args());
    }
}